name: app

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      coverage_excludes: '**/*.gen.dart **/*.g.dart **/bootstrap_config/*.dart lib/l10n/gen/app_localizations*.dart'